// <auto-generated />
using System;
using AnimalsWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalsWebAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20211214101245_Seeded_Data_In_Animal_And_AnimalType")]
    partial class Seeded_Data_In_Animal_And_AnimalType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AnimalsWebAPI.Data.Entities.Animal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("AnimalTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AnimalTypeID");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AnimalTypeID = 1,
                            Created = new DateTime(2021, 12, 14, 11, 12, 45, 22, DateTimeKind.Local).AddTicks(2593),
                            DateOfBirth = new DateTime(1975, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adam"
                        },
                        new
                        {
                            ID = 2,
                            AnimalTypeID = 2,
                            Created = new DateTime(2021, 12, 14, 11, 12, 45, 22, DateTimeKind.Local).AddTicks(2597),
                            DateOfBirth = new DateTime(1975, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Benke"
                        },
                        new
                        {
                            ID = 3,
                            AnimalTypeID = 3,
                            Created = new DateTime(2021, 12, 14, 11, 12, 45, 22, DateTimeKind.Local).AddTicks(2598),
                            DateOfBirth = new DateTime(1975, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Camilla"
                        },
                        new
                        {
                            ID = 4,
                            AnimalTypeID = 3,
                            Created = new DateTime(2021, 12, 14, 11, 12, 45, 22, DateTimeKind.Local).AddTicks(2600),
                            DateOfBirth = new DateTime(1975, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Daniela"
                        });
                });

            modelBuilder.Entity("AnimalsWebAPI.Data.Entities.AnimalType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfLegs")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("AnimalTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Created = new DateTime(2021, 12, 14, 11, 12, 45, 22, DateTimeKind.Local).AddTicks(2478),
                            Name = "Dog",
                            NumberOfLegs = 4
                        },
                        new
                        {
                            ID = 2,
                            Created = new DateTime(2021, 12, 14, 11, 12, 45, 22, DateTimeKind.Local).AddTicks(2521),
                            Name = "Ostrich",
                            NumberOfLegs = 2
                        },
                        new
                        {
                            ID = 3,
                            Created = new DateTime(2021, 12, 14, 11, 12, 45, 22, DateTimeKind.Local).AddTicks(2523),
                            Name = "Spider",
                            NumberOfLegs = 8
                        });
                });

            modelBuilder.Entity("AnimalsWebAPI.Data.Entities.Animal", b =>
                {
                    b.HasOne("AnimalsWebAPI.Data.Entities.AnimalType", null)
                        .WithMany("Animals")
                        .HasForeignKey("AnimalTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimalsWebAPI.Data.Entities.AnimalType", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
